WITH RECURSIVE ECOLI_GEN AS 
(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL 
    (
        SELECT D.ID, D.PARENT_ID, G.GENERATION + 1 AS GENERATION
        FROM ECOLI_DATA D JOIN ECOLI_GEN G
        ON D.PARENT_ID = G.ID
    )
)
SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM ECOLI_GEN
WHERE NOT ID IN (SELECT DISTINCT PARENT_ID
                FROM ECOLI_DATA
                WHERE PARENT_ID IS NOT NULl)
GROUP BY GENERATION
ORDER BY GENERATION

