WITH TEMP AS
(SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
 FROM ECOLI_DATA
 GROUP BY YEAR)
 
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, T.MAXSIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA JOIN TEMP T
ON YEAR(DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR, YEAR_DEV